version: "2"
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24

services:
  'tsung-1':
    image: cs_6_tsung_1.6.0
    hostname: tsung-1
    volumes:
      - ./wwwroot:/data/www/wwwroot
      - ~/.ssh/id_rsa.pub:/root/.ssh/authorized_keys
      - ~/.ssh/config:/root/.ssh/config
    networks:
      app_net:
        ipv4_address: 172.16.238.11
    extra_hosts:
      - "tsung-2:172.16.238.12"
      - "tsung-3:172.16.238.13"
  'tsung-2':
    image: cs_6_tsung_1.6.0
    hostname: tsung-2
    volumes:
      - ./wwwroot:/data/www/wwwroot
      - ~/.ssh/id_rsa.pub:/root/.ssh/authorized_keys
      - ~/.ssh/config:/root/.ssh/config
    networks:
      app_net:
        ipv4_address: 172.16.238.12
    extra_hosts:
      - "tsung-1:172.16.238.11"
      - "tsung-3:172.16.238.13"
  'tsung-3':
    image: cs_6_tsung_1.6.0
    hostname: tsung-3
    volumes:
      - ./wwwroot:/data/www/wwwroot
      - ~/.ssh/id_rsa.pub:/root/.ssh/authorized_keys
      - ~/.ssh/config:/root/.ssh/config
    networks:
      app_net:
        ipv4_address: 172.16.238.13
    extra_hosts:
      - "tsung-1:172.16.238.11"
      - "tsung-2:172.16.238.12"